name: Manage PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    permissions:
      pull-requests: write
      read:org: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #gh pr edit ${{ github.ref }} --add-assignee @cjdcordeiro-new-test/pr-review-team
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"team_reviewers":["pr-review-team"]}'
