name: Manage PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh pr edit ${{ github.ref_name }} --add-assignee @cjdcordeiro-new-test/pr-review-team

