name: Manage PRs

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/some_name_for_configs.yml' # Only needed if you use something other than .github/auto_assign.yml
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #run: |
          #gh pr edit ${{ github.ref }} --add-assignee @cjdcordeiro-new-test/pr-review-team
        uses: actions/github-script@v2
        with:
          script: |
            const team = 'pr-review-team';
            const token = process.env.GITHUB_TOKEN;

            const response = await github.rest.pulls.addReviewers({
              pull_id: context.payload.pull_id,
              team_reviewers: [team],
              token
            });

            console.log(response);
