name: test repo dispatch

on:
  repository_dispatch:
    types: [from-cjdc]
  workflow_dispatch:
  push:

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    steps:
      - run: echo hello
      - uses: actions/checkout@v3
        with:
          repo: https://git.launchpad.net/~ubuntu-docker-images/ubuntu-docker-images/+git/nginx
      - run: ls && pwd
      # - uses: cjdcordeiro/spread@master
