name: test pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - "ubuntu*"
jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    environment: test-env
    steps:
      - run: echo hello ${{ secrets.foo }}
