name: test repo dispatch

on:
  repository_dispatch:
    types: [from-cjdc]
  workflow_dispatch:
  push:

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    steps:
      - run: echo hello
      - uses: cjdcordeiro/spread@master
