name: test repo dispatch

on:
  status
jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
          echo ${{ github.event }}