name: test repo dispatch

on:
  repository_dispatch:
    types: [from-cjdc]
  workflow_dispatch:
  push:

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    steps:
      - if: ${{ env.FOO != '' }}
        env:
          FOO: 1
        run: echo hello
      - run: yq -V
      - uses: actions/checkout@v4
      - run: ls && pwd
      # - uses: cjdcordeiro/spread@master
