name: test pr

on:
  pull_request_target:

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    environment: test-env
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls
          cat .github/workflows/test.yml
      - run: echo hello ${{ secrets.foo }}
